function (setup_compilers)

  if (MSVC)
      list(APPEND CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /permissive- ")
  endif(MSVC)
  list(APPEND CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
  list(APPEND CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  list(APPEND CMAKE_INSTALL_RPATH "@loader_path/../Resources/libtorch")
  list(APPEND CMAKE_CXX_FLAGS "-Wall")
  list(APPEND CMAKE_CXX_FLAGS_DEBUG "-g")
  list(APPEND CMAKE_CXX_FLAGS_RELEASE "-O3 -march=native")
  if (APPLE)
    add_link_options("-Wl,-weak_reference_mismatches,weak")
  endif()
endfunction()
