name: Build

on:
  push:
    tags:
      - "v*"
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install needed dependencies
        run: sudo apt-get update && sudo apt-get install -y git cmake g++ libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libfreetype-dev libcurl4-openssl-dev libasound2-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup the build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: build
        run: cmake --build . --config Release -j 4

      - name: Compress
        working-directory: build/rave-vst_artefacts
        run: |
          mv Release RAVE_VST
          zip -r RAVE_VST_Ubuntu.zip RAVE_VST/AU RAVE_VST/Standalone RAVE_VST/VST3 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RAVE_VST_Ubuntu
          path: build/rave-vst_artefacts/RAVE_VST_Ubuntu.zip

  macos_arm64_build:
    runs-on: macos-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup the build
        run: |
          mkdir -p build
          cd build
          curl -L https://anaconda.org/pytorch/pytorch/2.0.1/download/osx-arm64/pytorch-2.0.1-py3.10_0.tar.bz2 | tar -xv
          mkdir torch
          mv lib/python3.10/site-packages/torch torch
          mv torch/torch torch/libtorch
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64
          
      - name: Build
        working-directory: build
        run: cmake --build . --config Release -j 4

      - name: Compress
        working-directory: build/rave-vst_artefacts
        run: |
          mv Release RAVE_VST
          zip -r RAVE_VST_MacOS_arm64.zip RAVE_VST/AU RAVE_VST/Standalone RAVE_VST/VST3 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RAVE_VS_macOS_arm64
          path: build/rave-vst_artefacts/RAVE_VST_MacOS_arm64.zip

  macos_x86_build:
    runs-on: macos-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup the build
        run: |
          mkdir -p build
          cd build
          curl -L https://download.pytorch.org/libtorch/cpu/libtorch-macos-2.0.1.zip | tar -xv
          mkdir torch
          mv libtorch torch
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64

      - name: Build
        working-directory: build
        run: cmake --build . --config Release -j 4

      - name: Compress
        working-directory: build/rave-vst_artefacts
        run: |
          mv Release RAVE_VST
          zip -r RAVE_VST_MacOS_x86.zip RAVE_VST/AU RAVE_VST/Standalone RAVE_VST/VST3 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RAVE_VS_macOS_x86_64
          path: build/rave-vst_artefacts/RAVE_VST_MacOS_x86.zip


  windows_build_x64:
    runs-on: windows-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup the build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: build
        run: cmake --build . --config Release -j 4

      - name: ls
        run: |
          ls build/rave-vst_artefacts
        
      - name: Compress
        working-directory: build/rave-vst_artefacts
        run: |
          mv Release RAVE_VST
          tar -czvf RAVE_VST_Windows_x64.tar.gz RAVE_VST

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RAVE_VS_Windows_x64
          path: build/rave-vst_artefacts/RAVE_VST_Windows_x64.tar.gz

  AutomaticRelease:
    runs-on: ubuntu-latest
    needs: [macos_x86_build, macos_arm64_build, windows_build_x64, ubuntu_build]
    steps:
      - name: Download build binaries
        uses: actions/download-artifact@v2
        with:
          name: RAVE_VST
      - name: Automated Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            RAVE_VST_Ubuntu.tar.gz
            RAVE_VST_MacOS_arm64.tar.gz
            RAVE_VST_MacOS_x86.tar.gz
            RAVE_VST_Windows_x64.tar.gz
